name: Build and push image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Build and push image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: [8.2, 8.2-dev, 8.3, 8.3-dev]
        include:
          - tag: 8.2
            php_version: 8.2
            target: base
            latest: false
          - tag: 8.2-dev
            php_version: 8.2
            target: dev
            latest: false
          - tag: 8.3
            php_version: 8.3
            target: base
            latest: true
          - tag: 8.3-dev
            php_version: 8.3
            target: dev
            latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME  }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_VENDOR }}/docker-php-apache
          tags: |
            type=raw,value=${{ matrix.tag }}
            type=raw,value=latest,enable=${{ matrix.latest }}

      - name: Build base image and push it to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
