name: Build and push image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_HOST }}/${{ secrets.REGISTRY_VENDOR }}/docker-php-apache:8.3

jobs:
  deploy:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_HOST }} --username ${{ secrets.REGISTRY_USERNAME  }} --password-stdin

      - name: Build base image and push it to registry
        run: |
          docker build --target base --tag ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}

      - name: Build dev image and push it to registry
        run: |
          docker build --target dev --tag ${{ env.IMAGE_NAME }}-dev .
          docker push ${{ env.IMAGE_NAME }}-dev
